name: hashing_methods_dart
description: A simple command-line application to analyze the performance of different hashing methods in Dart
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.9.0
dependencies:
  crypto: ^3.0.1
